<a href="https://colab.research.google.com/github/ND15/Algorithms/blob/main/Logistic_Regression_Gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [147]:
import numpy as np

In [148]:
from sklearn import datasets
iris = datasets.load_iris()

In [149]:
X = iris["data"][:, :]
y = iris["target"]

In [150]:
# sigmoid function
def sigmoid(z):
  deno = 1 + np.exp(-z)
  return 1/deno

In [151]:
def one_hot_encode(y):
  n = y.max() + 1
  m = len(y)
  y_one_hot = np.zeros((m, n))
  y_one_hot[np.arange(m), y] = 1
  return y_one_hot

In [152]:
# Add bias term to X
X_new = np.c_[np.ones((len(X), 1)), X]

In [153]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.3, random_state=42)

In [154]:
X_train[:10], y_train[:10]

(array([[1. , 5.5, 2.4, 3.7, 1. ],
        [1. , 6.3, 2.8, 5.1, 1.5],
        [1. , 6.4, 3.1, 5.5, 1.8],
        [1. , 6.6, 3. , 4.4, 1.4],
        [1. , 7.2, 3.6, 6.1, 2.5],
        [1. , 5.7, 2.9, 4.2, 1.3],
        [1. , 7.6, 3. , 6.6, 2.1],
        [1. , 5.6, 3. , 4.5, 1.5],
        [1. , 5.1, 3.5, 1.4, 0.2],
        [1. , 7.7, 2.8, 6.7, 2. ]]), array([1, 2, 2, 1, 2, 1, 2, 1, 0, 2]))

In [155]:
y_train_one_hot = one_hot_encode(y_train)
y_test_one_hot = one_hot_encode(y_test)

In [156]:
def Gradient_Descent(X, y, lr, n_iterations):
  m = len(X)
  features = X.shape[1]
  outputs = len(y[1])

  theta = np.random.randn(features, outputs)

  for iteration in range(n_iterations):
    hypo = X.dot(theta)
    # y_prob = softmax(hypo)
    y_prob = sigmoid(hypo)

    if iteration % 100 == 0:
      cost = -1/m * np.sum(y * np.log(y_prob) + (1 - y)*np.log(1 - y_prob))
      print(iteration, cost)

    error = y_prob - y
    gradients = 1/m * X.T.dot(error)
    theta = theta - lr * gradients
  
  return theta

In [157]:
theta = Gradient_Descent(X_train, y_train_one_hot, 0.1, 1000)

0 10.850362053279836
100 1.0194224920823411
200 0.8917297977326342
300 0.8222563303753565
400 0.7768298449902159
500 0.7448921314413318
600 0.7213683471554925
700 0.7034105692063504
800 0.6892908713876862
900 0.6779062711007677


In [158]:
theta

array([[ 0.20975716,  1.30012011, -1.57487281],
       [ 0.31521227,  0.15052946, -2.20955342],
       [ 2.26730676, -1.39312366, -1.75878242],
       [-3.32257034,  1.05380291,  3.30540815],
       [ 0.28965882, -2.29444327,  2.53854641]])

In [159]:
hypo = X_test.dot(theta)
y_prob = sigmoid(hypo)
y_pred = np.argmax(y_prob, axis=1)

In [160]:
np.concatenate((y_test.reshape(len(y_test), 1), y_pred.reshape(len(y_pred), 1)), 1)

array([[1, 1],
       [0, 0],
       [2, 2],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [2, 2],
       [1, 1],
       [1, 1],
       [2, 2],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [2, 2],
       [1, 1],
       [1, 1],
       [2, 2],
       [0, 0],
       [2, 2],
       [0, 0],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [2, 2],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [2, 2],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0]])

In [161]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

1.0

In [162]:
# single prediction
X_try = np.array([[1. , 5.5, 2.4, 3.7, 1. ]])
y_p = sigmoid(X_try.dot(theta))
np.argmax(y_p, axis=1)

array([1])