<a href="https://colab.research.google.com/github/ND15/Algorithms/blob/main/Logistic_Regression_Gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Implementation of **Gradient Descent** for **Logistic Regression**. 
But this may not work well for large dataset.

In [1286]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [1287]:
from sklearn import datasets
iris = datasets.load_iris()
X = iris["data"][:, 3:]
y = (iris['target']==2).astype(int)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [1288]:
def sigmoid(z):
  return 1 / (1 + np.exp(-z))

def softmax(z):
    return np.exp(z) / np.sum(np.exp(z), axis = 1, keepdims = True)

In [1289]:
def conv_label(z):
  return z.argmax(axis=1)

In [1290]:
def gradient_descent(X, y, n_iterations, alpha=0.01):
  theta = np.random.randn(2, 2)
  m = len(X)
  print(m)
  for i in range(n_iterations):
    gradients = (1 / m) * X.T.dot(softmax(X.dot(theta)) - y)
    theta = theta - (alpha/m) * gradients
  return theta

In [1291]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=12)

In [1292]:
y_b = y_train.reshape((len(y_train), 1))
X_train_new = np.c_[np.ones((len(X_train), 1)), X_train]
X_b = gradient_descent(X_train_new, y_b, 10000)
X_b.shape

120


(2, 2)

In [1293]:
X_test_new = np.c_[np.ones((len(X_test), 1)), X_test]
y_pred = X_test_new.dot(X_b)
print(y_pred.shape)
y_pred = conv_label(y_pred)
y_pred

(30, 2)


array([0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0])

In [1294]:
y_test

array([0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0])

In [1295]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9666666666666667

In [1296]:
X_b_p = np.c_[np.ones((len(X), 1)), X]
y = X_b_p.dot(X_b)
y = conv_label(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])